theme: jekyll-theme-minimal
title: ESSB Data Coffee Breaks
description: Calendar and resources for the ESSB Data Coffee Breasks at Erasmus University Rotterdam
logo: /assets/img/ESSB_datacoffeebreaks_logo.jpg

author:
  name:           'Eduard Klapwijk, ESSB Research Data Steward'
  url:            https://twitter.com/eduardklap
  
  github:
  repo:           https://github.com/eduardklap/essb-data-breaks/
